-- ─────────────────────────────────────────────────────────────────────────────
-- Avantra Carrier Services — combined schema setup.
--
-- Generated by concatenating supabase/migrations/*.sql in filename order.
-- Paste this whole file into the Supabase SQL editor to build the schema in
-- one shot. Every statement is idempotent, so re-running is safe.
--
-- The migrations directory remains the schema of record — regenerate this file
-- after adding one; do not hand-edit it.
-- ─────────────────────────────────────────────────────────────────────────────


-- ===========================================================================
-- 20260803_01_foundation.sql
-- ===========================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- Avantra Carrier Services — 01 Foundation: extensions, RLS helper spine,
-- profiles, company_settings, audit_log.
--
-- Run in the Supabase SQL editor in filename order. Every statement is
-- idempotent (safe to re-run). These migrations are the SCHEMA OF RECORD.
--
-- Business model reminder for anyone reading the schema cold: Avantra is a
-- dispatch-service AGENT, not a broker and not an asset carrier. Our CLIENTS are
-- motor carriers (owner-operators / small fleets). We source freight for them
-- from BROKERS, dispatch it on their trucks, invoice the broker on their behalf,
-- and bill the client a DISPATCH FEE. Money flows:
--     broker → client carrier (or their factor)        [the load pays them]
--     client → Avantra                                  [the dispatch fee pays us]
-- ─────────────────────────────────────────────────────────────────────────────

-- Allow the helper functions below to reference tables (profiles) created later
-- in this script — bodies are validated lazily, like pg_dump does. Session-only.
set check_function_bodies = off;

create extension if not exists pgcrypto;   -- gen_random_uuid()

-- ── Generic updated_at trigger ───────────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

-- ── RLS helper spine (all SECURITY DEFINER so they bypass RLS internally) ─────
create or replace function public.app_role()
returns text language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid()
$$;

create or replace function public.is_master()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce((select is_master_admin from public.profiles where id = auth.uid()), false)
$$;

-- The workhorse: is the caller Avantra staff (as opposed to a client-portal user)?
create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce(
    (select is_master_admin
       or role in ('admin','dispatcher','back_office','sales')
     from public.profiles where id = auth.uid()),
    false)
$$;

create or replace function public.has_role(variadic roles text[])
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce(
    (select is_master_admin or role = any(roles)
     from public.profiles where id = auth.uid()),
    false)
$$;

-- Drop EVERY existing policy on a table before recreating the intended set, so a
-- stale permissive policy can't survive a re-run.
create or replace function public._reset_policies(tbl text)
returns void language plpgsql as $$
declare p record;
begin
  for p in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = tbl
  loop
    execute format('drop policy if exists %I on public.%I', p.policyname, tbl);
  end loop;
end;
$$;

-- ── profiles ─────────────────────────────────────────────────────────────────
-- PK = auth.users.id. Auto-provisioned at signup (default 'pending'); role +
-- master flag are pinned against self-escalation by the trigger below.
--
-- Roles:
--   admin       — everything
--   dispatcher  — sources + books + dispatches loads, runs the board
--   back_office — invoicing, factoring, invoice tracing/AR, statements, paperwork
--   sales       — prospecting + client onboarding
--   client      — EXTERNAL: a carrier client logging into their own portal
--   pending / terminated — lifecycle states with no data access
create table if not exists public.profiles (
  id              uuid primary key references auth.users(id) on delete cascade,
  email           text,
  full_name       text,
  phone           text,
  role            text not null default 'pending'
                  check (role in ('admin','dispatcher','back_office','sales','client','pending','terminated')),
  is_master_admin boolean not null default false,
  mfa_enrolled    boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz
);
drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();

-- Auto-create a profile row when an auth user is created.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'pending')
  on conflict (id) do nothing;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- Pin role / is_master_admin unless the writer is the service role. RLS is
-- row-level, not column-level, so without this a user could PATCH their own row
-- to admin.
create or replace function public.prevent_profile_privilege_escalation()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if auth.role() = 'service_role' then
    return new;  -- service role (server, role-checked) may change anything
  end if;
  new.role := old.role;
  new.is_master_admin := old.is_master_admin;
  return new;
end;
$$;
drop trigger if exists trg_profiles_priv_esc on public.profiles;
create trigger trg_profiles_priv_esc before update on public.profiles
  for each row execute function public.prevent_profile_privilege_escalation();

alter table public.profiles enable row level security;
select public._reset_policies('profiles');
create policy profiles_select on public.profiles for select
  using (id = auth.uid() or public.is_staff());
create policy profiles_update on public.profiles for update
  using (id = auth.uid() or public.has_role('admin'))
  with check (id = auth.uid() or public.has_role('admin'));
create policy profiles_insert on public.profiles for insert
  with check (public.has_role('admin'));

-- ── company_settings (singleton) ─────────────────────────────────────────────
create table if not exists public.company_settings (
  id                 integer primary key default 1 check (id = 1),
  company_name       text not null default 'Avantra Carrier Services',
  company_identity   jsonb not null default '{}'::jsonb,  -- name/address/logo for PDFs
  role_permissions   jsonb not null default '{}'::jsonb,  -- consumed by @/lib/access
  billing_settings   jsonb not null default '{}'::jsonb,  -- remit-to / ACH for fee statements
  dispatch_defaults  jsonb not null default '{}'::jsonb,  -- default fee %, basis, minimum
  require_2fa        boolean not null default true,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz
);
insert into public.company_settings (id) values (1) on conflict (id) do nothing;
drop trigger if exists trg_company_settings_updated_at on public.company_settings;
create trigger trg_company_settings_updated_at before update on public.company_settings
  for each row execute function public.set_updated_at();

alter table public.company_settings enable row level security;
select public._reset_policies('company_settings');
-- Reads open to any authenticated user (role_permissions is needed everywhere);
-- writes admin/master only.
create policy company_settings_select on public.company_settings for select
  using (auth.uid() is not null);
create policy company_settings_write on public.company_settings for all
  using (public.has_role('admin')) with check (public.has_role('admin'));

-- ── audit_log (append-only, tamper-evident) ─────────────────────────────────
create table if not exists public.audit_log (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid references auth.users(id) on delete set null,
  action      text not null,
  table_name  text,
  record_id   text,
  old_value   jsonb,
  new_value   jsonb,
  created_at  timestamptz not null default now()
);
create index if not exists idx_audit_log_created_at on public.audit_log(created_at desc);
create index if not exists idx_audit_log_action on public.audit_log(action);
create index if not exists idx_audit_log_record on public.audit_log(table_name, record_id);

alter table public.audit_log enable row level security;
select public._reset_policies('audit_log');
-- INSERT allowed for any authenticated user, attributed to themselves. No UPDATE
-- or DELETE policy exists → the log is append-only. Reads: admin/back_office.
create policy audit_log_insert on public.audit_log for insert
  with check (user_id = auth.uid());
create policy audit_log_select on public.audit_log for select
  using (public.has_role('admin','back_office'));


-- ===========================================================================
-- 20260803_02_clients.sql
-- ===========================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- Avantra — 02 Clients: the carriers we dispatch FOR, plus their drivers,
-- equipment, factoring relationship, and onboarding checklist.
--
-- `clients` is the heart of the model. In Cryolane a carrier is a VENDOR you pay;
-- here a client carrier is the CUSTOMER you serve — you invoice brokers in their
-- name and bill them a dispatch fee. Depends on 01. Idempotent.
-- ─────────────────────────────────────────────────────────────────────────────

set check_function_bodies = off;

-- ── factoring_companies ──────────────────────────────────────────────────────
-- Most owner-operators factor their receivables. We submit invoices to the
-- client's factor and track funding, so the factor is a first-class entity.
create table if not exists public.factoring_companies (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  contact_name    text,
  email           text,
  phone           text,
  submission_email text,               -- where invoice packets get sent
  portal_url      text,
  advance_rate    numeric,             -- e.g. 95.00 (%)
  fee_percent     numeric,             -- e.g. 3.00 (%)
  notes           text,
  is_active       boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz
);
create unique index if not exists idx_factoring_companies_name on public.factoring_companies(lower(name));
drop trigger if exists trg_factoring_companies_updated_at on public.factoring_companies;
create trigger trg_factoring_companies_updated_at before update on public.factoring_companies
  for each row execute function public.set_updated_at();

alter table public.factoring_companies enable row level security;
select public._reset_policies('factoring_companies');
create policy factoring_companies_all on public.factoring_companies for all
  using (public.is_staff()) with check (public.is_staff());

-- ── clients (carrier clients we provide dispatch + back-office services to) ───
create sequence if not exists public.client_number_seq start with 1001;

create table if not exists public.clients (
  id                  uuid primary key default gen_random_uuid(),
  client_number       text unique,
  legal_name          text not null,
  dba_name            text,
  status              text not null default 'prospect'
                      check (status in ('prospect','onboarding','active','paused','terminated')),
  -- Authority / identity
  mc_number           text,
  dot_number          text,
  ein                 text,
  authority_status    text not null default 'unknown'
                      check (authority_status in ('active','pending','inactive','not_authorized','unknown')),
  authority_date      date,
  safety_rating       text,
  fmcsa_last_checked  timestamptz,
  -- Contact
  contact_name        text,
  phone               text,
  email               text,
  billing_email       text,
  address             text,
  city                text,
  state               text,
  zip                 text,
  -- Service agreement — the legal spine of the agent relationship
  agreement_signed_at date,
  poa_signed_at       date,            -- limited power of attorney (bill in their name)
  agreement_doc_path  text,            -- private `documents` bucket object path
  w9_on_file          boolean not null default false,
  coi_on_file         boolean not null default false,
  noa_on_file         boolean not null default false,   -- notice of assignment (factoring)
  -- Dispatch fee terms (snapshotted onto each load at booking)
  fee_type            text not null default 'percent' check (fee_type in ('percent','flat')),
  fee_percent         numeric not null default 10,
  fee_flat            numeric not null default 0,
  fee_basis           text not null default 'gross' check (fee_basis in ('gross','linehaul')),
  fee_minimum         numeric not null default 0,
  billing_cycle       text not null default 'weekly' check (billing_cycle in ('weekly','biweekly','monthly','per_load')),
  -- Factoring
  factoring_company_id uuid references public.factoring_companies(id) on delete set null,
  factors_invoices    boolean not null default false,
  -- Insurance (COI tracking lives in compliance_items; these are the quick-glance fields)
  insurance_provider  text,
  liability_amount    numeric,
  cargo_amount        numeric,
  insurance_expiry    date,
  -- Dispatch preferences — what the dispatcher needs to know before booking
  equipment_types     text[] not null default '{}',      -- Reefer / Dry Van / Flatbed …
  preferred_states    text[] not null default '{}',
  avoid_states        text[] not null default '{}',
  home_base_city      text,
  home_base_state     text,
  min_rate_per_mile   numeric,
  max_weekly_miles    numeric,
  hazmat              boolean not null default false,
  team                boolean not null default false,
  notes               text,
  -- Ownership
  assigned_dispatcher uuid references auth.users(id) on delete set null,
  onboarded_at        date,
  terminated_at       date,
  termination_reason  text,
  deleted_at          timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz
);
create index if not exists idx_clients_status on public.clients(status) where deleted_at is null;
create index if not exists idx_clients_dispatcher on public.clients(assigned_dispatcher);
create index if not exists idx_clients_mc on public.clients(mc_number);
create index if not exists idx_clients_name on public.clients(lower(legal_name));

create or replace function public.set_client_number()
returns trigger language plpgsql as $$
begin
  if new.client_number is null or new.client_number = '' then
    new.client_number := 'AC-' || nextval('public.client_number_seq');
  end if;
  return new;
end;
$$;
drop trigger if exists trg_clients_set_number on public.clients;
create trigger trg_clients_set_number before insert on public.clients
  for each row execute function public.set_client_number();
drop trigger if exists trg_clients_updated_at on public.clients;
create trigger trg_clients_updated_at before update on public.clients
  for each row execute function public.set_updated_at();

alter table public.clients enable row level security;
select public._reset_policies('clients');
create policy clients_staff_all on public.clients for all
  using (public.is_staff()) with check (public.is_staff());

-- ── Client-portal identity ───────────────────────────────────────────────────
-- A 'client' role profile is bound to exactly one client row. Every portal RLS
-- policy funnels through app_client_id() so a client can only ever see their own
-- data. Added here (not in 01) because it needs clients to exist for the FK.
alter table public.profiles
  add column if not exists client_id uuid references public.clients(id) on delete set null;

create or replace function public.app_client_id()
returns uuid language sql stable security definer set search_path = public as $$
  select client_id from public.profiles where id = auth.uid()
$$;

-- Clients may read their own record (never write it).
create policy clients_portal_select on public.clients for select
  using (id = public.app_client_id());

-- ── client_drivers ───────────────────────────────────────────────────────────
create table if not exists public.client_drivers (
  id              uuid primary key default gen_random_uuid(),
  client_id       uuid not null references public.clients(id) on delete cascade,
  full_name       text not null,
  phone           text,
  email           text,
  cdl_number      text,
  cdl_state       text,
  cdl_expiry      date,
  medical_expiry  date,
  hazmat_endorsed boolean not null default false,
  is_owner        boolean not null default false,   -- the O-O themself drives
  status          text not null default 'active' check (status in ('active','inactive','terminated')),
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz
);
create index if not exists idx_client_drivers_client on public.client_drivers(client_id);
create index if not exists idx_client_drivers_cdl_expiry on public.client_drivers(cdl_expiry) where cdl_expiry is not null;
drop trigger if exists trg_client_drivers_updated_at on public.client_drivers;
create trigger trg_client_drivers_updated_at before update on public.client_drivers
  for each row execute function public.set_updated_at();

alter table public.client_drivers enable row level security;
select public._reset_policies('client_drivers');
create policy client_drivers_staff_all on public.client_drivers for all
  using (public.is_staff()) with check (public.is_staff());
create policy client_drivers_portal_select on public.client_drivers for select
  using (client_id = public.app_client_id());

-- ── client_equipment (their trucks + trailers) ───────────────────────────────
create table if not exists public.client_equipment (
  id              uuid primary key default gen_random_uuid(),
  client_id       uuid not null references public.clients(id) on delete cascade,
  kind            text not null default 'truck' check (kind in ('truck','trailer')),
  unit_number     text,
  equipment_type  text,               -- Reefer / Dry Van / Flatbed / Step Deck …
  year            integer,
  make            text,
  model           text,
  vin             text,
  plate           text,
  plate_state     text,
  length_ft       integer,
  status          text not null default 'active' check (status in ('active','inactive','out_of_service')),
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz
);
create index if not exists idx_client_equipment_client on public.client_equipment(client_id, kind);
drop trigger if exists trg_client_equipment_updated_at on public.client_equipment;
create trigger trg_client_equipment_updated_at before update on public.client_equipment
  for each row execute function public.set_updated_at();

alter table public.client_equipment enable row level security;
select public._reset_policies('client_equipment');
create policy client_equipment_staff_all on public.client_equipment for all
  using (public.is_staff()) with check (public.is_staff());
create policy client_equipment_portal_select on public.client_equipment for select
  using (client_id = public.app_client_id());

-- ── client_onboarding_steps ──────────────────────────────────────────────────
-- The A-to-Z onboarding checklist. Seeded per client from a default template by
-- the app; each row is independently completable and auditable.
create table if not exists public.client_onboarding_steps (
  id           uuid primary key default gen_random_uuid(),
  client_id    uuid not null references public.clients(id) on delete cascade,
  step_key     text not null,          -- agreement | poa | w9 | coi | noa | authority | setup_packet …
  label        text not null,
  sort_order   integer not null default 0,
  is_required  boolean not null default true,
  completed_at timestamptz,
  completed_by uuid references auth.users(id) on delete set null,
  doc_path     text,
  notes        text,
  created_at   timestamptz not null default now()
);
create unique index if not exists idx_onboarding_client_step on public.client_onboarding_steps(client_id, step_key);
create index if not exists idx_onboarding_client on public.client_onboarding_steps(client_id, sort_order);

alter table public.client_onboarding_steps enable row level security;
select public._reset_policies('client_onboarding_steps');
create policy client_onboarding_staff_all on public.client_onboarding_steps for all
  using (public.is_staff()) with check (public.is_staff());
create policy client_onboarding_portal_select on public.client_onboarding_steps for select
  using (client_id = public.app_client_id());

-- ── client_notes (CRM timeline) ──────────────────────────────────────────────
create table if not exists public.client_notes (
  id         uuid primary key default gen_random_uuid(),
  client_id  uuid not null references public.clients(id) on delete cascade,
  body       text not null,
  kind       text not null default 'note' check (kind in ('note','call','email','meeting','issue')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists idx_client_notes_client on public.client_notes(client_id, created_at desc);

alter table public.client_notes enable row level security;
select public._reset_policies('client_notes');
create policy client_notes_staff_all on public.client_notes for all
  using (public.is_staff()) with check (public.is_staff());


-- ===========================================================================
-- 20260803_03_brokers_loads.sql
-- ===========================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- Avantra — 03 Brokers + Loads: the counterparties we book with, the central
-- load fact table, multi-stop support, and the check-call log.
--
-- Money on a load runs the OPPOSITE direction from a brokerage. The broker pays
-- the GROSS to our client (or their factor). We take a DISPATCH FEE off that
-- gross; net_to_client is what the carrier keeps. There is no margin — our
-- revenue is dispatch_fee, full stop. Depends on 01–02. Idempotent.
-- ─────────────────────────────────────────────────────────────────────────────

set check_function_bodies = off;

-- ── brokers (who pays the freight bill) ──────────────────────────────────────
create table if not exists public.brokers (
  id                uuid primary key default gen_random_uuid(),
  name              text not null,
  mc_number         text,
  dot_number        text,
  -- Contact
  contact_name      text,
  phone             text,
  after_hours_phone text,
  email             text,
  billing_email     text,
  address           text,
  city              text,
  state             text,
  zip               text,
  -- Credit / payment behaviour — what makes a broker safe to haul for
  payment_terms     text,                       -- "Net 30", "Quick Pay 2%" …
  days_to_pay       integer,                    -- observed average, updated from paid invoices
  credit_rating     text,                       -- free-text (Ansonia / broker credit score)
  credit_limit      numeric,
  -- Setup packet: are we able to invoice them on a client's behalf yet?
  packet_status     text not null default 'none'
                    check (packet_status in ('none','sent','pending','complete')),
  packet_completed_at date,
  -- Blocklist
  do_not_use        boolean not null default false,
  do_not_use_reason text,
  notes             text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz
);
create index if not exists idx_brokers_name on public.brokers(lower(name));
create index if not exists idx_brokers_mc on public.brokers(mc_number);
create index if not exists idx_brokers_dnu on public.brokers(do_not_use) where do_not_use = true;
drop trigger if exists trg_brokers_updated_at on public.brokers;
create trigger trg_brokers_updated_at before update on public.brokers
  for each row execute function public.set_updated_at();

alter table public.brokers enable row level security;
select public._reset_policies('brokers');
create policy brokers_staff_all on public.brokers for all
  using (public.is_staff()) with check (public.is_staff());

-- ── loads ────────────────────────────────────────────────────────────────────
-- Single-pickup/single-drop details live denormalized on the load itself (the
-- common case, and it keeps the board query to one table). Extra stops go in
-- load_stops; the denormalized columns always mirror the FIRST pickup and LAST
-- delivery so lists and the public tracking page never need the join.
create sequence if not exists public.load_number_seq start with 10001;

create table if not exists public.loads (
  id                 uuid primary key default gen_random_uuid(),
  load_number        text unique,
  status             text not null default 'sourced'
                     check (status in ('sourced','offered','booked','dispatched','at_pickup',
                                       'in_transit','at_delivery','delivered','docs_received',
                                       'invoiced','paid','cancelled','tonu')),
  -- Who it's for / who pays
  client_id          uuid references public.clients(id) on delete set null,
  client_name        text,
  broker_id          uuid references public.brokers(id) on delete set null,
  broker_name        text,
  broker_load_number text,
  source             text not null default 'broker_direct'
                     check (source in ('dat','truckstop','broker_direct','client','relationship','other')),
  -- Assignment (the client's own driver + equipment)
  driver_id          uuid references public.client_drivers(id) on delete set null,
  driver_name        text,
  truck_id           uuid references public.client_equipment(id) on delete set null,
  trailer_id         uuid references public.client_equipment(id) on delete set null,
  -- Pickup (first stop)
  shipper_name       text,
  shipper_address    text,
  pickup_city        text,
  pickup_state       text,
  pickup_zip         text,
  pickup_date        date,
  pickup_time        text,
  pickup_appt        text,
  -- Delivery (last stop)
  consignee_name     text,
  consignee_address  text,
  delivery_city      text,
  delivery_state     text,
  delivery_zip       text,
  delivery_date      date,
  delivery_time      text,
  delivery_appt      text,
  -- Freight
  commodity          text,
  weight             numeric,
  temperature        text,
  equipment_type     text,
  miles              numeric,
  stop_count         integer not null default 2,
  -- Money the BROKER pays (all revenue belongs to the client, not to us)
  line_haul          numeric not null default 0,
  fuel_surcharge     numeric not null default 0,
  accessorials       numeric not null default 0,
  detention          numeric not null default 0,
  lumper             numeric not null default 0,
  other_charges      numeric not null default 0,
  gross_total        numeric not null default 0,   -- maintained by recalc_load_money()
  -- Dispatch fee terms, SNAPSHOTTED from the client at booking so changing the
  -- client's plan later never rewrites history.
  fee_type           text not null default 'percent' check (fee_type in ('percent','flat')),
  fee_percent        numeric not null default 10,
  fee_flat           numeric not null default 0,
  fee_basis          text not null default 'gross' check (fee_basis in ('gross','linehaul')),
  fee_minimum        numeric not null default 0,
  fee_manual         boolean not null default false,  -- true = dispatch_fee entered by hand
  fee_waived         boolean not null default false,
  fee_waived_reason  text,
  dispatch_fee       numeric not null default 0,   -- OUR revenue. maintained by trigger
  net_to_client      numeric not null default 0,   -- gross_total − dispatch_fee
  -- References / paperwork
  ref_number         text,
  po_number          text,
  bol_number         text,
  seal_number        text,
  rate_con_path      text,                          -- private `documents` object path
  rate_con_received_at timestamptz,
  pod_path           text,
  pod_received_at    timestamptz,
  -- Lifecycle timestamps
  offered_at         timestamptz,
  booked_at          timestamptz,
  dispatched_at      timestamptz,
  picked_up_at       timestamptz,
  delivered_at       timestamptz,
  cancelled_at       timestamptz,
  cancel_reason      text,
  -- Public tracking
  tracking_token     uuid not null default gen_random_uuid(),
  tracking_active    boolean not null default true,
  notes              text,
  dispatcher_id      uuid references auth.users(id) on delete set null,
  deleted_at         timestamptz,
  deleted_by         uuid references auth.users(id) on delete set null,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz
);
create unique index if not exists idx_loads_tracking_token on public.loads(tracking_token);
create index if not exists idx_loads_status on public.loads(status) where deleted_at is null;
create index if not exists idx_loads_client on public.loads(client_id) where deleted_at is null;
create index if not exists idx_loads_broker on public.loads(broker_id) where deleted_at is null;
create index if not exists idx_loads_driver on public.loads(driver_id) where deleted_at is null;
create index if not exists idx_loads_pickup_date on public.loads(pickup_date desc);
create index if not exists idx_loads_lane on public.loads(pickup_state, delivery_state);

-- Auto load number.
create or replace function public.set_load_number()
returns trigger language plpgsql as $$
begin
  if new.load_number is null or new.load_number = '' then
    new.load_number := 'AV-' || nextval('public.load_number_seq');
  end if;
  return new;
end;
$$;

-- ── The money engine ─────────────────────────────────────────────────────────
-- A trigger rather than generated columns: the fee needs a minimum, a manual
-- override, and a waive path, none of which a generated column can express
-- (and Postgres forbids a generated column referencing another one anyway).
create or replace function public.recalc_load_money()
returns trigger language plpgsql as $$
declare
  v_gross numeric;
  v_base  numeric;
  v_fee   numeric;
begin
  v_gross := coalesce(new.line_haul,0) + coalesce(new.fuel_surcharge,0)
           + coalesce(new.accessorials,0) + coalesce(new.detention,0)
           + coalesce(new.lumper,0) + coalesce(new.other_charges,0);

  if new.fee_waived or new.status = 'cancelled' then
    v_fee := 0;
  elsif new.fee_manual then
    v_fee := coalesce(new.dispatch_fee, 0);          -- respect the hand-entered value
  else
    v_base := case when new.fee_basis = 'linehaul'
                   then coalesce(new.line_haul, 0)
                   else v_gross end;
    v_fee  := case when new.fee_type = 'flat'
                   then coalesce(new.fee_flat, 0)
                   else round(v_base * coalesce(new.fee_percent, 0) / 100.0, 2) end;
    -- A minimum only applies once there's actually money on the load, so a blank
    -- draft doesn't show a fee owed.
    if coalesce(new.fee_minimum, 0) > 0 and v_base > 0 then
      v_fee := greatest(v_fee, new.fee_minimum);
    end if;
  end if;

  new.gross_total   := round(v_gross, 2);
  new.dispatch_fee  := round(v_fee, 2);
  new.net_to_client := round(v_gross - v_fee, 2);
  return new;
end;
$$;

drop trigger if exists trg_loads_set_number on public.loads;
create trigger trg_loads_set_number before insert on public.loads
  for each row execute function public.set_load_number();
drop trigger if exists trg_loads_money on public.loads;
create trigger trg_loads_money before insert or update on public.loads
  for each row execute function public.recalc_load_money();
drop trigger if exists trg_loads_updated_at on public.loads;
create trigger trg_loads_updated_at before update on public.loads
  for each row execute function public.set_updated_at();

alter table public.loads enable row level security;
select public._reset_policies('loads');
create policy loads_staff_all on public.loads for all
  using (public.is_staff()) with check (public.is_staff());
-- Portal: a client sees only their own loads, read-only.
create policy loads_portal_select on public.loads for select
  using (client_id = public.app_client_id() and deleted_at is null);

-- ── load_stops (stops 2..n on a multi-stop load) ─────────────────────────────
create table if not exists public.load_stops (
  id            uuid primary key default gen_random_uuid(),
  load_id       uuid not null references public.loads(id) on delete cascade,
  seq           integer not null default 1,
  stop_type     text not null default 'pickup' check (stop_type in ('pickup','delivery')),
  facility_name text,
  address       text,
  city          text,
  state         text,
  zip           text,
  stop_date     date,
  stop_time     text,
  appt_number   text,
  reference     text,
  instructions  text,
  arrived_at    timestamptz,
  departed_at   timestamptz,
  created_at    timestamptz not null default now()
);
create index if not exists idx_load_stops_load on public.load_stops(load_id, seq);

alter table public.load_stops enable row level security;
select public._reset_policies('load_stops');
create policy load_stops_staff_all on public.load_stops for all
  using (public.is_staff()) with check (public.is_staff());
create policy load_stops_portal_select on public.load_stops for select
  using (exists (select 1 from public.loads l
                 where l.id = load_id and l.client_id = public.app_client_id()));

-- ── load_check_calls ─────────────────────────────────────────────────────────
-- Dispatcher check-ins. Rows flagged is_public surface on the anonymous
-- /track/<token> page through a whitelisting RPC (see migration 06).
create table if not exists public.load_check_calls (
  id           uuid primary key default gen_random_uuid(),
  load_id      uuid not null references public.loads(id) on delete cascade,
  occurred_at  timestamptz not null default now(),
  location     text,
  city         text,
  state        text,
  status_note  text,                 -- "loaded, rolling", "at receiver door 12" …
  eta          timestamptz,
  temperature  text,                 -- reefer set-point confirmation
  miles_out    numeric,
  notes        text,                 -- INTERNAL — never exposed publicly
  is_public    boolean not null default true,
  created_by   uuid references auth.users(id) on delete set null,
  created_at   timestamptz not null default now()
);
create index if not exists idx_check_calls_load on public.load_check_calls(load_id, occurred_at desc);

alter table public.load_check_calls enable row level security;
select public._reset_policies('load_check_calls');
create policy check_calls_staff_all on public.load_check_calls for all
  using (public.is_staff()) with check (public.is_staff());
create policy check_calls_portal_select on public.load_check_calls for select
  using (exists (select 1 from public.loads l
                 where l.id = load_id and l.client_id = public.app_client_id()));


-- ===========================================================================
-- 20260803_04_billing.sql
-- ===========================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- Avantra — 04 Billing. Two distinct money flows, deliberately separate tables:
--
--   invoices           → we bill the BROKER, in our CLIENT's name, for the load.
--                        The money lands with the client (or their factor), not
--                        with us. We track it because chasing it IS the service.
--   client_statements  → we bill our CLIENT for the dispatch fees they owe us.
--                        This is Avantra's actual revenue.
--
-- invoice_traces is the collections/"invoice tracing" activity log — the audit
-- trail that proves the chasing happened. Depends on 01–03. Idempotent.
-- ─────────────────────────────────────────────────────────────────────────────

set check_function_bodies = off;

-- ── invoices (broker-facing, issued on the client's behalf) ──────────────────
create sequence if not exists public.invoice_number_seq start with 5001;

create table if not exists public.invoices (
  id                 uuid primary key default gen_random_uuid(),
  invoice_number     text unique,
  load_id            uuid references public.loads(id) on delete set null,
  client_id          uuid references public.clients(id) on delete set null,
  broker_id          uuid references public.brokers(id) on delete set null,
  status             text not null default 'draft'
                     check (status in ('draft','sent','factored','partial','paid',
                                       'overdue','disputed','written_off','void')),
  amount             numeric not null default 0,
  amount_paid        numeric not null default 0,
  -- Dates / terms
  issued_date        date,
  due_date           date,
  terms              text,                       -- "Net 30"
  sent_at            timestamptz,
  sent_to            text,
  -- Factoring: submitted to the client's factor, who advances against it
  factored_at        timestamptz,
  factoring_company_id uuid references public.factoring_companies(id) on delete set null,
  factoring_reference text,
  funded_at          timestamptz,
  funded_amount      numeric,
  factoring_fee      numeric,
  -- Settlement
  paid_date          date,
  payment_method     text check (payment_method in ('ach','check','wire','factor','other')),
  payment_reference  text,
  -- Collections / invoice tracing
  last_traced_at     timestamptz,
  trace_count        integer not null default 0,
  next_follow_up     date,
  dispute_reason     text,
  -- Paperwork
  invoice_pdf_path   text,                       -- private `documents` object path
  packet_path        text,                       -- invoice + BOL + POD combined packet
  -- Void audit trio
  voided_at          timestamptz,
  voided_by          uuid references auth.users(id) on delete set null,
  void_reason        text,
  notes              text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz
);
-- One live invoice per load. A voided invoice frees the load to be re-invoiced.
create unique index if not exists idx_invoices_one_per_load
  on public.invoices(load_id) where load_id is not null and status <> 'void';
create index if not exists idx_invoices_status on public.invoices(status);
create index if not exists idx_invoices_client on public.invoices(client_id);
create index if not exists idx_invoices_broker on public.invoices(broker_id);
create index if not exists idx_invoices_due on public.invoices(due_date)
  where status in ('sent','factored','partial','overdue');

create or replace function public.set_invoice_number()
returns trigger language plpgsql as $$
begin
  if new.invoice_number is null or new.invoice_number = '' then
    new.invoice_number := 'INV-' || nextval('public.invoice_number_seq');
  end if;
  return new;
end;
$$;
drop trigger if exists trg_invoices_set_number on public.invoices;
create trigger trg_invoices_set_number before insert on public.invoices
  for each row execute function public.set_invoice_number();
drop trigger if exists trg_invoices_updated_at on public.invoices;
create trigger trg_invoices_updated_at before update on public.invoices
  for each row execute function public.set_updated_at();

alter table public.invoices enable row level security;
select public._reset_policies('invoices');
create policy invoices_staff_all on public.invoices for all
  using (public.is_staff()) with check (public.is_staff());
create policy invoices_portal_select on public.invoices for select
  using (client_id = public.app_client_id());

-- ── invoice_traces (the collections activity log) ────────────────────────────
-- Every chase attempt against a broker invoice. Keeping this append-only-ish and
-- attributed is what lets us show a client exactly what we did to get them paid.
create table if not exists public.invoice_traces (
  id            uuid primary key default gen_random_uuid(),
  invoice_id    uuid not null references public.invoices(id) on delete cascade,
  traced_at     timestamptz not null default now(),
  method        text not null default 'call' check (method in ('call','email','portal','letter','other')),
  contact_name  text,
  contact_info  text,
  outcome       text not null default 'no_answer'
                check (outcome in ('no_answer','left_message','promised_payment','in_process',
                                   'disputed','short_paid','paid','escalated','other')),
  promised_date date,
  notes         text,
  created_by    uuid references auth.users(id) on delete set null,
  created_at    timestamptz not null default now()
);
create index if not exists idx_invoice_traces_invoice on public.invoice_traces(invoice_id, traced_at desc);

-- Keep the invoice's rollup counters honest without the app having to remember.
create or replace function public.bump_invoice_trace_counters()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  update public.invoices
     set trace_count    = (select count(*) from public.invoice_traces where invoice_id = new.invoice_id),
         last_traced_at = (select max(traced_at) from public.invoice_traces where invoice_id = new.invoice_id),
         next_follow_up = coalesce(new.promised_date, next_follow_up)
   where id = new.invoice_id;
  return new;
end;
$$;
drop trigger if exists trg_invoice_traces_bump on public.invoice_traces;
create trigger trg_invoice_traces_bump after insert on public.invoice_traces
  for each row execute function public.bump_invoice_trace_counters();

alter table public.invoice_traces enable row level security;
select public._reset_policies('invoice_traces');
create policy invoice_traces_staff_all on public.invoice_traces for all
  using (public.is_staff()) with check (public.is_staff());
create policy invoice_traces_portal_select on public.invoice_traces for select
  using (exists (select 1 from public.invoices i
                 where i.id = invoice_id and i.client_id = public.app_client_id()));

-- ── client_statements (Avantra's revenue: the dispatch-fee bill) ─────────────
create sequence if not exists public.statement_number_seq start with 2001;

create table if not exists public.client_statements (
  id                uuid primary key default gen_random_uuid(),
  statement_number  text unique,
  client_id         uuid not null references public.clients(id) on delete cascade,
  period_start      date not null,
  period_end        date not null,
  status            text not null default 'draft'
                    check (status in ('draft','sent','partial','paid','overdue','void')),
  load_count        integer not null default 0,
  total_gross       numeric not null default 0,   -- gross the client billed on these loads
  total_fees        numeric not null default 0,   -- our fees on those loads
  adjustments       numeric not null default 0,   -- credits/discounts (negative) or add-ons
  amount_due        numeric not null default 0,   -- total_fees + adjustments
  amount_paid       numeric not null default 0,
  issued_date       date,
  due_date          date,
  sent_at           timestamptz,
  paid_date         date,
  payment_method    text check (payment_method in ('ach','check','wire','card','other')),
  payment_reference text,
  pdf_path          text,
  voided_at         timestamptz,
  voided_by         uuid references auth.users(id) on delete set null,
  void_reason       text,
  notes             text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz
);
create index if not exists idx_statements_client on public.client_statements(client_id, period_end desc);
create index if not exists idx_statements_status on public.client_statements(status);

create or replace function public.set_statement_number()
returns trigger language plpgsql as $$
begin
  if new.statement_number is null or new.statement_number = '' then
    new.statement_number := 'ST-' || nextval('public.statement_number_seq');
  end if;
  return new;
end;
$$;
drop trigger if exists trg_statements_set_number on public.client_statements;
create trigger trg_statements_set_number before insert on public.client_statements
  for each row execute function public.set_statement_number();
drop trigger if exists trg_statements_updated_at on public.client_statements;
create trigger trg_statements_updated_at before update on public.client_statements
  for each row execute function public.set_updated_at();

alter table public.client_statements enable row level security;
select public._reset_policies('client_statements');
create policy client_statements_staff_all on public.client_statements for all
  using (public.is_staff()) with check (public.is_staff());
create policy client_statements_portal_select on public.client_statements for select
  using (client_id = public.app_client_id());

-- ── statement_lines ──────────────────────────────────────────────────────────
create table if not exists public.statement_lines (
  id           uuid primary key default gen_random_uuid(),
  statement_id uuid not null references public.client_statements(id) on delete cascade,
  load_id      uuid references public.loads(id) on delete set null,
  kind         text not null default 'fee' check (kind in ('fee','adjustment','credit','service')),
  description  text not null,
  load_gross   numeric not null default 0,
  amount       numeric not null default 0,   -- what the client owes for this line
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now()
);
create index if not exists idx_statement_lines_statement on public.statement_lines(statement_id, sort_order);
-- A load's fee can only land on one statement, so a re-run can't double-bill.
create unique index if not exists idx_statement_lines_one_fee_per_load
  on public.statement_lines(load_id) where load_id is not null and kind = 'fee';

-- Recompute the statement header whenever its lines change.
create or replace function public.recalc_statement_totals()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_stmt uuid;
begin
  v_stmt := coalesce(new.statement_id, old.statement_id);
  update public.client_statements s
     set load_count  = (select count(*) from public.statement_lines
                        where statement_id = v_stmt and kind = 'fee'),
         total_gross = (select coalesce(sum(load_gross),0) from public.statement_lines
                        where statement_id = v_stmt and kind = 'fee'),
         total_fees  = (select coalesce(sum(amount),0) from public.statement_lines
                        where statement_id = v_stmt and kind = 'fee'),
         adjustments = (select coalesce(sum(amount),0) from public.statement_lines
                        where statement_id = v_stmt and kind <> 'fee'),
         amount_due  = (select coalesce(sum(amount),0) from public.statement_lines
                        where statement_id = v_stmt)
   where s.id = v_stmt;
  return null;
end;
$$;
drop trigger if exists trg_statement_lines_recalc on public.statement_lines;
create trigger trg_statement_lines_recalc
  after insert or update or delete on public.statement_lines
  for each row execute function public.recalc_statement_totals();

alter table public.statement_lines enable row level security;
select public._reset_policies('statement_lines');
create policy statement_lines_staff_all on public.statement_lines for all
  using (public.is_staff()) with check (public.is_staff());
create policy statement_lines_portal_select on public.statement_lines for select
  using (exists (select 1 from public.client_statements s
                 where s.id = statement_id and s.client_id = public.app_client_id()));


-- ===========================================================================
-- 20260803_05_compliance_services.sql
-- ===========================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- Avantra — 05 Compliance + Service Requests.
--
-- compliance_items is a single generic expiry ledger covering everything Avantra
-- watches on a client's behalf: operating authority, liability/cargo COIs, IFTA,
-- UCR, MCS-150, BOC-3, drug consortium, 2290, CDLs, medical cards, annual
-- inspections. One table (not one per kind) so the watchdog is a single query and
-- adding a new kind never needs a migration.
--
-- service_requests is the back-office work queue that makes "A-to-Z services"
-- real: every non-load thing a client asks us to do, tracked, assigned, and
-- optionally billable onto their statement. Depends on 01–04. Idempotent.
-- ─────────────────────────────────────────────────────────────────────────────

set check_function_bodies = off;

-- ── compliance_items ─────────────────────────────────────────────────────────
create table if not exists public.compliance_items (
  id            uuid primary key default gen_random_uuid(),
  client_id     uuid not null references public.clients(id) on delete cascade,
  -- What the item hangs off. client_id is ALWAYS set (even for a driver's CDL) so
  -- the compliance board can filter by client without extra joins.
  entity_type   text not null default 'client'
                check (entity_type in ('client','driver','equipment')),
  entity_id     uuid,
  kind          text not null,        -- authority | liability_insurance | cargo_insurance |
                                      -- ifta | ucr | mcs150 | boc3 | drug_consortium |
                                      -- form_2290 | cdl | medical_card | annual_inspection | other
  label         text,                 -- human override, else the app renders the kind
  status        text not null default 'pending'
                check (status in ('ok','expiring','expired','missing','pending','not_applicable')),
  provider      text,                 -- insurer / consortium / filing agent
  reference     text,                 -- policy #, filing #, confirmation #
  amount        numeric,              -- coverage limit where relevant
  effective_date date,
  expiry_date   date,
  doc_path      text,                 -- private `documents` object path
  last_checked_at timestamptz,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz
);
create index if not exists idx_compliance_client on public.compliance_items(client_id, kind);
create index if not exists idx_compliance_expiry on public.compliance_items(expiry_date)
  where expiry_date is not null;
create index if not exists idx_compliance_status on public.compliance_items(status);
create unique index if not exists idx_compliance_unique
  on public.compliance_items(client_id, entity_type, coalesce(entity_id, '00000000-0000-0000-0000-000000000000'::uuid), kind);

drop trigger if exists trg_compliance_updated_at on public.compliance_items;
create trigger trg_compliance_updated_at before update on public.compliance_items
  for each row execute function public.set_updated_at();

-- Derive status from the expiry date on every write, so the board is never stale
-- because someone forgot to also flip the status field.
create or replace function public.derive_compliance_status()
returns trigger language plpgsql as $$
begin
  if new.status = 'not_applicable' then
    return new;                                    -- explicit opt-out wins
  end if;
  if new.expiry_date is null then
    if new.effective_date is null and new.reference is null and new.doc_path is null then
      new.status := 'missing';
    else
      new.status := 'ok';
    end if;
  elsif new.expiry_date < current_date then
    new.status := 'expired';
  elsif new.expiry_date <= current_date + interval '30 days' then
    new.status := 'expiring';
  else
    new.status := 'ok';
  end if;
  return new;
end;
$$;
drop trigger if exists trg_compliance_status on public.compliance_items;
create trigger trg_compliance_status before insert or update on public.compliance_items
  for each row execute function public.derive_compliance_status();

alter table public.compliance_items enable row level security;
select public._reset_policies('compliance_items');
create policy compliance_staff_all on public.compliance_items for all
  using (public.is_staff()) with check (public.is_staff());
create policy compliance_portal_select on public.compliance_items for select
  using (client_id = public.app_client_id());

-- ── service_requests ─────────────────────────────────────────────────────────
create sequence if not exists public.service_request_seq start with 101;

create table if not exists public.service_requests (
  id            uuid primary key default gen_random_uuid(),
  request_number text unique,
  client_id     uuid references public.clients(id) on delete cascade,
  kind          text not null default 'other',
                -- new_authority | authority_reinstatement | ifta_registration | ifta_filing |
                -- ucr | mcs150_update | boc3 | drug_consortium | form_2290 | insurance_quote |
                -- factoring_setup | broker_setup | permit | dispute | notary | other
  title         text not null,
  description   text,
  status        text not null default 'open'
                check (status in ('open','in_progress','waiting_client','waiting_third_party',
                                  'blocked','done','cancelled')),
  priority      text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  assigned_to   uuid references auth.users(id) on delete set null,
  requested_by  uuid references auth.users(id) on delete set null,
  due_date      date,
  started_at    timestamptz,
  completed_at  timestamptz,
  -- Billable services flow onto the client's next statement as a 'service' line.
  billable      boolean not null default false,
  fee_amount    numeric not null default 0,
  billed_at     timestamptz,
  statement_id  uuid references public.client_statements(id) on delete set null,
  outcome       text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz
);
create index if not exists idx_service_requests_client on public.service_requests(client_id);
create index if not exists idx_service_requests_status on public.service_requests(status, priority);
create index if not exists idx_service_requests_assignee on public.service_requests(assigned_to)
  where status not in ('done','cancelled');
create index if not exists idx_service_requests_billable on public.service_requests(billable)
  where billable = true and billed_at is null;

create or replace function public.set_service_request_number()
returns trigger language plpgsql as $$
begin
  if new.request_number is null or new.request_number = '' then
    new.request_number := 'SR-' || nextval('public.service_request_seq');
  end if;
  return new;
end;
$$;
drop trigger if exists trg_service_requests_set_number on public.service_requests;
create trigger trg_service_requests_set_number before insert on public.service_requests
  for each row execute function public.set_service_request_number();
drop trigger if exists trg_service_requests_updated_at on public.service_requests;
create trigger trg_service_requests_updated_at before update on public.service_requests
  for each row execute function public.set_updated_at();

alter table public.service_requests enable row level security;
select public._reset_policies('service_requests');
create policy service_requests_staff_all on public.service_requests for all
  using (public.is_staff()) with check (public.is_staff());
create policy service_requests_portal_select on public.service_requests for select
  using (client_id = public.app_client_id());

-- ── service_request_updates (per-request timeline) ───────────────────────────
create table if not exists public.service_request_updates (
  id          uuid primary key default gen_random_uuid(),
  request_id  uuid not null references public.service_requests(id) on delete cascade,
  body        text not null,
  status_from text,
  status_to   text,
  created_by  uuid references auth.users(id) on delete set null,
  created_at  timestamptz not null default now()
);
create index if not exists idx_sr_updates_request on public.service_request_updates(request_id, created_at desc);

alter table public.service_request_updates enable row level security;
select public._reset_policies('service_request_updates');
create policy sr_updates_staff_all on public.service_request_updates for all
  using (public.is_staff()) with check (public.is_staff());
create policy sr_updates_portal_select on public.service_request_updates for select
  using (exists (select 1 from public.service_requests r
                 where r.id = request_id and r.client_id = public.app_client_id()));


-- ===========================================================================
-- 20260803_06_documents_tracking.sql
-- ===========================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- Avantra — 06 Documents + public tracking.
--
-- The `documents` storage bucket is PRIVATE. Nothing in the app ever calls
-- getPublicUrl(); files are read exclusively through short-lived signed URLs
-- minted server-side by /api/doc-url. The table below is metadata only — the
-- bytes live in storage.
--
-- The /track/<token> page is anonymous, so it reads through SECURITY DEFINER
-- RPCs that whitelist safe columns. Rates, fees, and net-to-client are NEVER
-- exposed — a broker holding a tracking link must not be able to see what our
-- client is netting, or what we charge. Depends on 01–05. Idempotent.
-- ─────────────────────────────────────────────────────────────────────────────

set check_function_bodies = off;

-- ── documents (metadata for objects in the private `documents` bucket) ───────
create table if not exists public.documents (
  id            uuid primary key default gen_random_uuid(),
  entity_type   text not null
                check (entity_type in ('client','driver','equipment','load','broker',
                                       'invoice','statement','service_request','company')),
  entity_id     uuid,
  -- Denormalized so portal RLS is a single column compare rather than a
  -- polymorphic join per entity_type.
  client_id     uuid references public.clients(id) on delete cascade,
  doc_type      text not null default 'other',
                -- rate_con | bol | pod | invoice | w9 | coi | authority | agreement |
                -- poa | noa | cdl | medical | inspection | lumper_receipt | scale | other
  file_path     text not null,        -- bare object path in the private bucket
  file_name     text,
  mime_type     text,
  size_bytes    bigint,
  expiry_date   date,                 -- for COIs and other expiring paperwork
  is_client_visible boolean not null default true,
  notes         text,
  uploaded_by   uuid references auth.users(id) on delete set null,
  created_at    timestamptz not null default now()
);
create index if not exists idx_documents_entity on public.documents(entity_type, entity_id);
create index if not exists idx_documents_client on public.documents(client_id);
create index if not exists idx_documents_type on public.documents(doc_type);
create index if not exists idx_documents_expiry on public.documents(expiry_date)
  where expiry_date is not null;

alter table public.documents enable row level security;
select public._reset_policies('documents');
create policy documents_staff_all on public.documents for all
  using (public.is_staff()) with check (public.is_staff());
create policy documents_portal_select on public.documents for select
  using (client_id = public.app_client_id() and is_client_visible = true);

-- ── The private bucket ───────────────────────────────────────────────────────
-- public = false. Signed URLs are minted by the service role in /api/doc-url,
-- which is why no broad storage.objects policy is granted to end users.
insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do update set public = false;

-- Staff may upload / read / delete objects in the bucket via their own session
-- (the client-side uploader); everyone else goes through the signed-URL route.
drop policy if exists documents_bucket_staff_all on storage.objects;
create policy documents_bucket_staff_all on storage.objects for all
  to authenticated
  using (bucket_id = 'documents' and public.is_staff())
  with check (bucket_id = 'documents' and public.is_staff());

-- ── Public tracking RPCs ─────────────────────────────────────────────────────
-- Whitelisted columns only. Deliberately omits line_haul, gross_total,
-- dispatch_fee, net_to_client, broker identity, and internal notes.
create or replace function public.get_load_tracking(p_token uuid)
returns table (
  load_number     text,
  status          text,
  equipment_type  text,
  client_name     text,
  pickup_city     text,
  pickup_state    text,
  pickup_date     date,
  delivery_city   text,
  delivery_state  text,
  delivery_date   date,
  commodity       text,
  temperature     text,
  stop_count      integer,
  tracking_active boolean
)
language sql stable security definer set search_path = public as $$
  select load_number, status, equipment_type, client_name,
         pickup_city, pickup_state, pickup_date,
         delivery_city, delivery_state, delivery_date,
         commodity, temperature, stop_count, tracking_active
  from public.loads
  where tracking_token = p_token
    and tracking_active = true
    and deleted_at is null
$$;
revoke all on function public.get_load_tracking(uuid) from public;
grant execute on function public.get_load_tracking(uuid) to anon, authenticated;

-- Check-in feed for the tracking page: only is_public rows, and never the
-- internal `notes` column.
create or replace function public.get_load_tracking_events(p_token uuid)
returns table (occurred_at timestamptz, location text, city text, state text,
               status_note text, temperature text, eta timestamptz)
language sql stable security definer set search_path = public as $$
  select cc.occurred_at, cc.location, cc.city, cc.state,
         cc.status_note, cc.temperature, cc.eta
  from public.load_check_calls cc
  join public.loads l on l.id = cc.load_id
  where l.tracking_token = p_token
    and l.tracking_active = true
    and l.deleted_at is null
    and cc.is_public = true
  order by cc.occurred_at desc
  limit 50
$$;
revoke all on function public.get_load_tracking_events(uuid) from public;
grant execute on function public.get_load_tracking_events(uuid) to anon, authenticated;


-- ===========================================================================
-- 20260908_07_leads.sql
-- ===========================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- Avantra — 07 Leads: enquiries from the marketing site (avantracs.com).
--
-- The marketing site is a SEPARATE deploy but writes into this same project, so
-- a lead lands in the dispatch queue rather than an inbox somebody has to
-- remember to check.
--
-- Security posture: the website has NO browser-side Supabase client and no anon
-- key. Its /api/lead route writes with the service role, server-side only. So
-- there is deliberately NO anon INSERT policy here — the table has no public
-- write surface at all, and spam control lives in the route (honeypot + rate
-- limit) rather than in RLS.
--
-- Depends on 01 (helpers) and 02 (clients). Idempotent.
-- ─────────────────────────────────────────────────────────────────────────────

set check_function_bodies = off;

create table if not exists public.leads (
  id            uuid primary key default gen_random_uuid(),
  -- Who got in touch
  name          text not null,
  company       text,
  email         text not null,
  phone         text,
  mc_number     text,
  equipment     text,
  truck_count   integer,
  message       text,
  -- Where from
  source        text not null default 'website'
                check (source in ('website','referral','phone','load_board','other')),
  submitted_ip  text,                 -- abuse triage only; never displayed
  -- Working the lead
  status        text not null default 'new'
                check (status in ('new','contacted','quoted','won','lost','spam')),
  assigned_to   uuid references auth.users(id) on delete set null,
  notes         text,
  contacted_at  timestamptz,
  -- Set when the lead becomes a real client, so the link survives conversion.
  converted_client_id uuid references public.clients(id) on delete set null,
  converted_at  timestamptz,
  lost_reason   text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz
);

create index if not exists idx_leads_status on public.leads(status, created_at desc);
create index if not exists idx_leads_created on public.leads(created_at desc);
create index if not exists idx_leads_email on public.leads(lower(email));

drop trigger if exists trg_leads_updated_at on public.leads;
create trigger trg_leads_updated_at before update on public.leads
  for each row execute function public.set_updated_at();

-- Stamp contacted_at the first time a lead leaves 'new', so nobody has to
-- remember to set it and response-time reporting stays honest.
create or replace function public.stamp_lead_contacted()
returns trigger language plpgsql as $$
begin
  if new.status is distinct from old.status
     and old.status = 'new'
     and new.status <> 'new'
     and new.contacted_at is null then
    new.contacted_at := now();
  end if;
  if new.converted_client_id is not null and new.converted_at is null then
    new.converted_at := now();
  end if;
  return new;
end;
$$;
drop trigger if exists trg_leads_contacted on public.leads;
create trigger trg_leads_contacted before update on public.leads
  for each row execute function public.stamp_lead_contacted();

alter table public.leads enable row level security;
select public._reset_policies('leads');

-- Staff only. No anon policy by design: the website never touches this table
-- from a browser, so granting public INSERT would create an abuse surface that
-- buys nothing.
create policy leads_staff_all on public.leads for all
  using (public.is_staff()) with check (public.is_staff());


-- ===========================================================================
-- 20260909_08_security_hardening.sql
-- ===========================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- Avantra — 08 Security hardening.
--
-- Three findings from the pre-launch audit, all confirmed against the live
-- database. Every one of them is a case of code and schema drifting apart.
--
--  1. prevent_profile_privilege_escalation() pinned role and is_master_admin,
--     but migration 02 later added profiles.client_id and made it the tenancy
--     key for the whole client portal. The trigger was never updated, so any
--     authenticated user could PATCH their own client_id and read another
--     carrier's entire book.
--
--  2. company_settings was readable by every authenticated user. The same row
--     carries billing_settings, which holds Avantra's ACH routing and account
--     numbers. Signup is open, so the audience for those was "anyone with an
--     email address".
--
--  3. login_attempts is read and written by /api/auth/login-track but exists in
--     no migration. The lockout has never worked.
--
-- Depends on 01 and 02. Idempotent.
-- ─────────────────────────────────────────────────────────────────────────────

set check_function_bodies = off;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Pin every column a user must not be able to grant themselves.
--
-- RLS is ROW-level, not column-level: profiles_update lets a user write their
-- own row, and nothing stopped them choosing which columns. role and
-- is_master_admin were pinned; client_id and mfa_enrolled were not.
--
--   client_id    is the tenancy key. app_client_id() reads it, and roughly a
--                dozen portal policies funnel through that — clients,
--                client_drivers, client_equipment, client_onboarding_steps,
--                loads, load_stops, load_check_calls, invoices,
--                client_statements, statement_lines, compliance_items,
--                service_requests, documents. Setting it to another carrier's
--                uuid hands over their loads, rates, invoices, statements,
--                driver CDL numbers and documents.
--
--   mfa_enrolled is what the middleware trusts when deciding whether to force
--                /setup-2fa. Self-attested, it let the account switch off the
--                control that protects it.
--
-- Admin paths are unaffected: /api/users uses the service role, which returns
-- early above.
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.prevent_profile_privilege_escalation()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if auth.role() = 'service_role' then
    return new;  -- service role (server, role-checked) may change anything
  end if;
  new.role            := old.role;
  new.is_master_admin := old.is_master_admin;
  new.client_id       := old.client_id;
  new.mfa_enrolled    := old.mfa_enrolled;
  return new;
end;
$$;

drop trigger if exists trg_profiles_priv_esc on public.profiles;
create trigger trg_profiles_priv_esc before update on public.profiles
  for each row execute function public.prevent_profile_privilege_escalation();

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Close company_settings, and hand out only the two fields that genuinely
--    need to be readable by everyone.
--
-- The old policy was `using (auth.uid() is not null)`, justified by
-- role_permissions being "needed everywhere". That is true, but RLS cannot hand
-- out one column and withhold another — so it also handed out billing_settings.
--
-- SELECT is now admin/back_office only: the settings page is admin, and billing
-- generation is back_office. Everything else reads get_app_config() below.
-- ─────────────────────────────────────────────────────────────────────────────
alter table public.company_settings enable row level security;
select public._reset_policies('company_settings');

create policy company_settings_select on public.company_settings for select
  using (public.has_role('admin', 'back_office'));
create policy company_settings_write on public.company_settings for all
  using (public.has_role('admin')) with check (public.has_role('admin'));

-- The narrow read. Returns ONLY the two non-sensitive fields the app needs on
-- every request — never company_identity and never billing_settings. Being
-- SECURITY DEFINER it bypasses the policy above, which is the entire point:
-- a client-portal or pending user can resolve their permissions and the 2FA
-- requirement without being able to see Avantra's bank details.
create or replace function public.get_app_config()
returns jsonb language sql stable security definer set search_path = public as $$
  select coalesce(
    (select jsonb_build_object(
              'role_permissions', coalesce(role_permissions, '{}'::jsonb),
              'require_2fa',      coalesce(require_2fa, true))
       from public.company_settings
      order by id
      limit 1),
    jsonb_build_object('role_permissions', '{}'::jsonb, 'require_2fa', true))
$$;

revoke all on function public.get_app_config() from public;
grant execute on function public.get_app_config() to authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. The account-lockout store.
--
-- Columns match exactly what /api/auth/login-track upserts. Only the service
-- role touches this table, so RLS is enabled with NO policies at all: the
-- service role bypasses RLS, and every other caller is denied by default. That
-- also keeps the failed-login history of every user account away from the
-- browser, which is the right posture for it.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.login_attempts (
  email           text primary key,
  failed_count    integer not null default 0,
  locked_until    timestamptz,
  last_attempt_at timestamptz not null default now()
);

-- Lets a cleanup job find stale rows without a sequential scan.
create index if not exists idx_login_attempts_last on public.login_attempts(last_attempt_at desc);

alter table public.login_attempts enable row level security;
select public._reset_policies('login_attempts');
-- Intentionally no policies. See above.


-- ===========================================================================
-- 20260909_09_money_correctness.sql
-- ===========================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- Avantra — 09 Money correctness.
--
-- Two audit findings, both about money, both confirmed against the code.
--
--  1. Voiding a fee statement permanently stranded its loads. The uniqueness
--     guard idx_statement_lines_one_fee_per_load has no status predicate, so a
--     fee line reserved its load forever. The invoice side got this right —
--     idx_invoices_one_per_load carries `where ... status <> 'void'`, with the
--     comment "A voided invoice frees the load to be re-invoiced" — but a
--     statement line's status lives on the PARENT row, and a partial index
--     cannot reference another table. Hence the denormalized flag below.
--
--     The consequence was not cosmetic: void a statement cut for the wrong
--     period and those loads can never be billed again through the UI, because
--     the generator's scan excludes any load with a fee line regardless of
--     whether that line's statement still counts. That is Avantra's own revenue
--     silently becoming unbillable.
--
--  2. Recording a second payment OVERWROTE the first. `amount_paid: amt` is a
--     replacement, and "is it paid in full" compared a single remittance
--     against the whole total rather than the outstanding balance. $400 then
--     $600 against a $1,000 statement left amount_paid = 600, status stuck at
--     'partial', $400 of phantom AR on the books, and a client still being
--     chased for money they had already sent. Both sides had it: client
--     statements and broker invoices.
--
--     Accumulating in app code would swap that bug for a lost-update race
--     between two people posting cheques at once, so the read-modify-write
--     happens here, in one statement, under the row lock the UPDATE takes.
--
-- Depends on 03 and 04. Idempotent.
-- ─────────────────────────────────────────────────────────────────────────────

set check_function_bodies = off;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Let a voided statement release its loads.
-- ─────────────────────────────────────────────────────────────────────────────
alter table public.statement_lines
  add column if not exists voided boolean not null default false;

-- Anything already sitting under a voided header is released by this backfill.
update public.statement_lines sl
   set voided = true
  from public.client_statements cs
 where sl.statement_id = cs.id
   and cs.status = 'void'
   and sl.voided = false;

-- Swap the guard for one that ignores released lines. Same protection against
-- double-billing a live load; no longer a life sentence.
drop index if exists public.idx_statement_lines_one_fee_per_load;
create unique index if not exists idx_statement_lines_one_fee_per_load
  on public.statement_lines(load_id)
  where load_id is not null and kind = 'fee' and not voided;

-- Keep the flag true to the parent's status, so nobody has to remember to set
-- it and a future void path cannot forget.
create or replace function public.sync_statement_line_void()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.status is distinct from old.status then
    update public.statement_lines
       set voided = (new.status = 'void')
     where statement_id = new.id
       and voided is distinct from (new.status = 'void');
  end if;
  return new;
end;
$$;
drop trigger if exists trg_statement_void_lines on public.client_statements;
create trigger trg_statement_void_lines after update on public.client_statements
  for each row execute function public.sync_statement_line_void();

-- A line added to an already-void statement inherits its state rather than
-- re-reserving the load.
create or replace function public.inherit_statement_line_void()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  new.voided := coalesce(
    (select status = 'void' from public.client_statements where id = new.statement_id),
    false);
  return new;
end;
$$;
drop trigger if exists trg_statement_line_inherit_void on public.statement_lines;
create trigger trg_statement_line_inherit_void before insert on public.statement_lines
  for each row execute function public.inherit_statement_line_void();

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Payments accumulate, atomically.
--
-- Both functions are SECURITY INVOKER on purpose: the caller's RLS still
-- decides whether they may touch the row. These exist to make the arithmetic
-- correct and race-free, not to widen access.
-- ─────────────────────────────────────────────────────────────────────────────

-- Client → Avantra. This is our revenue.
create or replace function public.record_statement_payment(
  p_statement_id uuid,
  p_amount       numeric,
  p_paid_date    date    default null,
  p_method       text    default null,
  p_reference    text    default null
) returns public.client_statements
language plpgsql security invoker set search_path = public as $$
declare rec public.client_statements;
begin
  if p_amount is null or p_amount <= 0 then
    raise exception 'Payment amount must be greater than zero';
  end if;

  update public.client_statements s
     set amount_paid       = coalesce(s.amount_paid, 0) + p_amount,
         status            = case
                               when coalesce(s.amount_paid, 0) + p_amount >= s.amount_due
                                 then 'paid'
                               else 'partial'
                             end,
         paid_date         = coalesce(p_paid_date, current_date),
         payment_method    = coalesce(p_method, s.payment_method),
         payment_reference = coalesce(p_reference, s.payment_reference)
   where s.id = p_statement_id
     and s.status <> 'void'
  returning s.* into rec;

  if rec.id is null then
    raise exception 'Statement not found, already voided, or not yours to edit';
  end if;
  return rec;
end;
$$;

-- Broker → the client carrier. NOT our money; we only bill and chase it.
create or replace function public.record_invoice_payment(
  p_invoice_id uuid,
  p_amount     numeric,
  p_paid_date  date    default null,
  p_method     text    default null,
  p_reference  text    default null
) returns public.invoices
language plpgsql security invoker set search_path = public as $$
declare rec public.invoices;
begin
  if p_amount is null or p_amount <= 0 then
    raise exception 'Payment amount must be greater than zero';
  end if;

  update public.invoices i
     set amount_paid       = coalesce(i.amount_paid, 0) + p_amount,
         status            = case
                               when coalesce(i.amount_paid, 0) + p_amount >= i.amount
                                 then 'paid'
                               else 'partial'
                             end,
         paid_date         = coalesce(p_paid_date, current_date),
         payment_method    = coalesce(p_method, i.payment_method),
         payment_reference = coalesce(p_reference, i.payment_reference)
   where i.id = p_invoice_id
     and i.status <> 'void'
  returning i.* into rec;

  if rec.id is null then
    raise exception 'Invoice not found, already voided, or not yours to edit';
  end if;

  -- Settling the load follows the invoice, and only once it is fully paid.
  -- In the function so it cannot drift out of step with the status above.
  if rec.status = 'paid' and rec.load_id is not null then
    update public.loads set status = 'paid' where id = rec.load_id;
  end if;

  return rec;
end;
$$;
